### ISSUE TITLE
建立统一文档入口

### ISSUE THREAD

**Issue by Ding-Fan** [geekapk-r/Talk#3]
文档都去哪儿了？从 https://github.com/geekapk/GeekPage 看到的 https://github.com/geekapk/GeekPage/blob/master/dev 这里是空的！

**Comment by Ding-Fan** [comment]
https://github.com/geekapk/GeekApkR/wiki 这个也是空的！

**Comment by duangsuse** [comment]
1. 那个是老的社团，我不再维护了...
2. GeekApk 现在没有可用的文档，但也有一些临时文档在 geekapk-r/ServerR 处可以看到，Core 组里也可以看到
3. 你想要什么文档，如果要贡献后端代码的话欢迎加入
